### ISSUE TITLE
Run example with fpm

### ISSUE THREAD

**Issue by Simkern** [nekStab/LightKrylov#51]
Since @loiseaujc added the GL example I tried running it directly with `fpm run` but I have not been able to with the current `fpm.toml`. Is there a trick that I am missing? 

To make it work, I had to disable the automatic discovery of the examples and define the example as a regular executable:

`fpm.toml`
```
[...]

auto-examples = false

[...]

[[executable]]

#---------------------------------------------------------
#-----     SETUP FOR THE GINZBURG-LANDAU EXAMPLE     -----
#---------------------------------------------------------

name = "Ginzburg-Landau"
source-dir = "example/ginzburg_landau"

[executable.dependencies]
rklib = { git="https://github.com/jacobwilliams/rklib.git" }
```

and then I can run the example with
```
fpm run Ginzburg-Landau
```

**Comment by loiseaujc** [comment]
The command recommended by `fpm` is

```
fpm run --example Ginzburg-Landau
```

I've just double-checked and it works on my laptop. I am currently writing the new version of the `README.md` where I'll mention these. I'll also write dedicated `README.md` files for each example.
