### ISSUE TITLE
Block Arnoldi iteration

### ISSUE THREAD

**Issue by loiseaujc** [nekStab/LightKrylov#6]
Implementation of the block Arnoldi algorithm. Use cases :

- Moment-matching ROM procedure for LTI systems with multiple inputs and multiple outputs.

This is not high on the priority list as we first need to start developing the LTI ROM package.

**Comment by ricardofrantz** [comment]
In the documentation branch, I added a skeleton for the routine and a sketch for the Krylov-Schur routine based on LAPACK's Schur routine.
