### ISSUE TITLE
Setup GitHub Actions for Continuous Integration

### ISSUE THREAD

**Issue by loiseaujc** [nekStab/LightKrylov#9]

**Comment by ricardofrantz** [comment]
I submitted a pull request of a first sketch, but it has not been executed yet.

**Comment by loiseaujc** [comment]
Maybe [this](https://github.com/fortran-lang/setup-fpm) can be useful?

**Comment by ricardofrantz** [comment]
yes, I am using it:

https://github.com/nekStab/LightKrylov/blob/ricardofrantz-patch-1/.github/workflows/gcc.yml

I dont know why this haven't entered the main branch.

**Comment by loiseaujc** [comment]
Can we close this issue ?

**Comment by ricardofrantz** [comment]
yes, you just need to accept the badge on the README.md and we can also delete the two additional branches
